name: MT_inpainting_diffuser
channels:
- defaults
- conda-forge

dependencies:
  - python>3.10
  - pip==24.0
  - pip:
    - torch==2.3.1
    - numpy==1.26.4 
    - gymnasium==0.29.1
    - minari==0.4.3 
    - wandb==0.17.3
    - mujoco==3.1.6
    - einops==0.8.0
    - scipy==1.14.0
    - h5py==3.11.0
    - imageio==2.34.2
    - imageio[ffmpeg]
    - matplotlib